SWE573_Project/urls.py
from django.urls import path, include
from SWE573_Project.views import mainpage
from SWE573_Project.views import tag, tag_ajax
from SWE573_Project.views import details
from SWE573_Project.views import report
from SWE573_Project.views import advancedSearch
# from SWE573_Project.views.comment import AddCommentView, CommentListView, AddAnnotateView
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from SWE573_Project.views import search
from SWE573_Project.views import DetailsTag


urlpatterns = [
    path('login', auth_views.LoginView.as_view(
        template_name='pages/login.html'
    ), name='login'),
    path('aboutus', TemplateView.as_view(
        template_name='pages/aboutus.html'
    ), name='aboutus'),
    path('', mainpage, name='homepage'),
    path('tag/<int:article_id>', tag, name='tag'),
    path('tag_ajax/<int:article_id>', tag_ajax, name='tag_ajax'),
    path('details/<slug:slug>', details.as_view(), name='details'),
    # path('details/<int:article_id>/newcomment', AddCommentView.as_view(template_name='pages/add_comment.html'), name='add_comment'),
    # path('details/<int:article_id>/comments', CommentListView.as_view(template_name='pages/comment.html'), name='comment'),
    # path('details/<int:article_id>/newannotation',AddAnnotateView.as_view(template_name='pages/annotate.html'), name='annotate'),
    path('report/<int:article_id>', report, name='report'),
    path('search', search, name='search'),
    path('', include('account.urls')),


    path('advancedsearch', advancedSearch, name='advancedSearch'),

]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls')),
    path('', include('SWE573_Project.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

SWE573_Project/models/ActivityModel.py
from django.db import models
from django.db.models import JSONField


class Activity(models.Model):

    activity_JSON = JSONField()

SWE573_Project/models/TagModel.py
from django.db import models

class TagModel(models.Model):
    name = models.CharField(max_length=255 ,blank=False)
    user = models.ForeignKey('account.CustomUserModel', on_delete=models.CASCADE ,related_name= 'tags', null=True)
    url = models.URLField(blank=True)




    class Meta:
        db_table = 'tags'
        verbose_name_plural = 'Tags'
        verbose_name = 'Tag'

    def __str__(self):
        return self.name

SWE573_Project/views/advancedSearch.py
from django.shortcuts import render
from SWE573_Project.models import ArticleModel
from django.core.paginator import Paginator
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from account.models import CustomUserModel
import datetime
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.shortcuts import render
from plotly.offline import plot
import plotly.graph_objects as go


@login_required(login_url="/login")
def advancedSearch(request):
    x = datetime.datetime.now()
    from_date = 1980
    to_date = x.year
    diff = to_date - from_date
    date_list = [from_date + i for i in range(diff + 1)]

    advancedSearchText = request.GET.get('advancedSearch')

    fromYear = request.GET.get('fromYear')
    toYear = request.GET.get('toYear')

    if fromYear:
        fromYear = fromYear
    else:
        fromYear = from_date

    if toYear:
        toYear = toYear
    else:
        toYear = to_date


    articles = ArticleModel.objects.order_by('-id')
    order = request.GET.get('orderArticles')
    if order == "newestFirst":
        articles = ArticleModel.objects.order_by('-publish_date')
    elif order == 'oldestFirst':
        articles = ArticleModel.objects.order_by('publish_date')

    tagAnnotationChoice = request.GET.get('tagAnnotationChoice')

    if advancedSearchText:
        if fromYear:
            if toYear:
                if tagAnnotationChoice == "includeTag":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)|
                         Q(tags__name__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()
                elif tagAnnotationChoice == "includeAnnotation":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)|
                         Q(tags__name__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()
                elif tagAnnotationChoice == "includeBoth":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)|
                         Q(tags__name__icontains=advancedSearchText) |
                         Q(tags__name__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()
                elif tagAnnotationChoice == "onlyTag":
                    articles = articles.filter(
                        (Q(tags__name__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()
                elif tagAnnotationChoice == "onlyAnnotation":
                    articles = articles.filter(
                        (Q(tags__name__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()
                elif tagAnnotationChoice == "onlyBoth":
                    articles = articles.filter(
                        (Q(tags__name__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()
                elif tagAnnotationChoice == "none":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()
                else:
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()

            else:
                if tagAnnotationChoice == "includeTag":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)|
                         Q(tags__name__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear)
                    ).distinct()
                elif tagAnnotationChoice == "includeAnnotation":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)|
                         Q(articleannotation__body__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear)
                    ).distinct()
                elif tagAnnotationChoice == "includeBoth":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)|
                         Q(tags__name__icontains=advancedSearchText) |
                         Q(articleannotation__body__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear)
                    ).distinct()
                elif tagAnnotationChoice == "onlyTag":
                    articles = articles.filter(
                        (Q(tags__name__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear)
                    ).distinct()
                elif tagAnnotationChoice == "onlyAnnotation":
                    articles = articles.filter(
                        (Q(articleannotation__body__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear)
                    ).distinct()
                elif tagAnnotationChoice == "onlyBoth":
                    articles = articles.filter(
                        (Q(tags__name__icontains=advancedSearchText) |
                         Q(articleannotation__body__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear)
                    ).distinct()
                elif tagAnnotationChoice == "none":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear)
                    ).distinct()
                else:
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)) &
                        Q(publish_date__year__gte=fromYear)
                    ).distinct()
        else:
            if toYear:
                if tagAnnotationChoice == "includeTag":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)|
                         Q(tags__name__icontains=advancedSearchText)) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()
                elif tagAnnotationChoice == "includeAnnotation":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)|
                         Q(articleannotation__body__icontains=advancedSearchText)) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()
                elif tagAnnotationChoice == "includeBoth":
                    articles = articles.filter(
                        (Q(title__icontains=advancedSearchText) |
                         Q(body__icontains=advancedSearchText) |
                         Q(keywords__icontains=advancedSearchText)|
                         Q(tags__name__icontains=advancedSearchText) |
                         Q(articleannotation__body__icontains=advancedSearchText)) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()
                elif tagAnnotationChoice == "onlyTag":
                    articles = articles.filter(
                        (Q(tags__name__icontains=advancedSearchText)) &
                        Q(publish_date__year__lte=toYear)
                    ).distinct()

SWE573_Project/views/annotations.py
# from django.http import HttpResponse
# from django.shortcuts import get_object_or_404, render
#
# from SWE573_Project.models import AnnotateMed, ArticleAnnotation
#
#
# def annotations(request, json_annotations=AnnotateMed.annotation_json):
#     AnnotateMed.objects.create(annotation_json=json_annotations)
#     if request.method == 'GET':
#         return render(request, 'pages/annotations.html')

SWE573_Project/views/annotator.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.shortcuts import redirect, render, get_object_or_404

from SWE573_Project.forms import CommentForm, TagForm
from SWE573_Project.models import ArticleAnnotation, AnnotationModel, ArticleModel


@login_required(login_url="/login")
def annotate(request, article_id):
    form = TagForm()
    if request.method == 'POST':
        if 'annotateBtn' in request.POST:  # TODO: it should be button id for tag request - Ask Akın
            # TODO: Fix detail.js for selection
            selected_text = request.POST['annotation-section']
            print(selected_text)
            wiki_tags = TagForm(request.POST)  # TODO: Call wikidata tags
            selection_start = request.POST['startIndex']
            selection_end = request.POST['endIndex']
            tag = wiki_tags.save()  # TODO: Save tag annotation  # Save wikidata tags to tag

            ArticleAnnotation.objects.get_or_create(article=article_id,
                                                    target=selected_text,
                                                    tag=tag,
                                                    start_index=selection_start,
                                                    end_index=selection_end
                                                    )

            context = {
                'form': form
            }
    return render(request, 'pages/tag.html')


def save_annotation(self, article_id, tag_id, startIndex, endIndex):
    json = {
        "@context": "http://www.w3.org/ns/anno.jsonld",
        "id": annotation_uri,
        "type": "Annotation",
        "body": [{
            "type": "TextualBody",
            "value": tag_qid,
            "purpose": "tagging"
        }],
        "target": {
            # TODO: Get the URL of article id http://127.0.0.1:8000
            "source": "http://127.0.0.1:8000/details/" + article_slug,
            "selector": {
                "type": "TextPositionSelector",
                "start": startIndex,
                "end": endIndex
            }
        }
    }

    annotation = AnnotationModel(annotation_json=json)
    annotation.save()





# @login_required
# def comment(request):
#     if request.method == 'POST':
#         form = CommentForm(request.POST)
#         if form.is_valid():
#             comment = form.cleaned_data["CommentForm"]
#             a = ArticleAnnotation(comment)
#             a.save()
#
#             return render(request, 'details', {'form': CommentForm})

SWE573_Project/views/createnewuser.py
from django.shortcuts import render, redirect
from account.forms import creationForm
from django.contrib import messages
from django.contrib.auth import login, authenticate #bunlar kayıt olduğu an login olsun diye kullanılıyor
from django.contrib.auth.decorators import login_required


def createnewuser(request):
    if request.method == 'POST':
        form = creationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = creationForm()
    return render(request, 'pages/createaccount.html', context={
        'form': form
    })

SWE573_Project/views/detailstag.py
from django.shortcuts import render, redirect
from SWE573_Project.forms.TagForm import TagForm
from SWE573_Project.models import ArticleModel, TagModel
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView


class DetailsTag(CreateView):
    model = TagModel
    form_class = TagForm
    template_name = 'details.html'
    #fields = '__all__'

    @login_required(login_url="/login")
    def DetailsTag(request, article_id):
        form = TagForm()
        if request.method == 'POST':
            form = TagForm(request.POST)
            if form.is_valid():
                user_id = request.user.id
                cleaned_info = form.cleaned_data
                i = TagModel.objects.filter(name=cleaned_info['name'])
                if not i.exists():
                    i = form.save(user_id=user_id, article_id=article_id)
                else:
                    i = i.first()
                article = ArticleModel.objects.get(id=article_id)
                article.tags.add(i)
                return redirect('details', article.slug)

        context = {
            'form': form
        }
        return render(request, 'pages/details.html', context=context)

SWE573_Project/views/login.py
from django.contrib.auth import login
from django.shortcuts import redirect

def loginView(request):
    login(request)
    return redirect('homepage')

SWE573_Project/templates/pages/aboutus.html
{% extends 'base.html' %} <!--bir bas html dosyası oluşturduk çünkü hepsini üstüne kullanıcaz config seetings dir üstünde güncellemesi var-->


{% block title %} About Us {% endblock %} <!--sayfanın başlığı-->

{% block content %} 
   
This project is developed for Boğaziçi University SWE573 course.


{% endblock %}

SWE573_Project/templates/pages/add_comment.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} Comments {% endblock %}

{% block content %} 

<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="../../static/css/details.css" type="text/css">
</head>

<body>
<div class="annotation_list"> New Comment</br>
    <div class="content-section">
    </br>
        <form method="POST">
        {{ form.errors }}
        {% csrf_token %} 
        <fieldset class="form-group">
            {{ form | crispy }}
        </fieldset>
      </br>
          <div class="form-group">
            <button class="btn btn-outline-secondary" type="submit">Comment</button>
            <a href=""><button type="button" class="btn btn-outline-secondary">Cancel</button></a>
          </div>
      </form></br>
    </div> 
  </div>
</body>

{% endblock %}

SWE573_Project/templates/pages/annotations.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>ANNOTATIONS</h2>
</body>
</html>

SWE573_Project/templates/pages/comment.html
{% extends 'base.html' %} 
{% load static %}

{% block content %} 

<head>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
    <link rel="stylesheet" href="../../static/css/details.css" type="text/css">
</head>

<body>
{% for comment in comments %}
<div class="card mb-3">
    <div class="row g-0">
        <div class="col-sm-12">
            <div id="full-text" class="card-body mb-3">
                <h6 class="text-muted">Comment by {{ user.username }} on {{ comment.created | date:"F d, Y"}}</h6>
                <p id="paragraph" class="card-text">{{ article.title }}</p>
                <p id="paragraph" class="card-text">{{ comment.body }}</p>
                <button class="like__btn">
                    <span id="likeicon"><i class="far fa-thumbs-up"></i></span>
                    <span id="countup">0</span>
                </button>
                <button class="dislike__btn">
                    <span id="dislikeicon"><i class="far fa-thumbs-down"></i></span>
                    <span id="countdown">0</span>
                </button>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<script src="../../static/js/details.js"></script> 
</body>

{% endblock %}

SWE573_Project/templates/pages/createaccount.html
{% extends 'base.html' %} <!--bir bas html dosyası oluşturduk çünkü hepsini üstüne kullanıcaz config seetings dir üstünde güncellemesi var-->
{% load crispy_forms_tags %} <!--crispy formları kullanabilmek için önce indirdik pipenv install diyip ardından html dosyalarına da koyuyoruz-->


{% block title %} Create Account {% endblock %} <!--sayfanın başlığı-->

{% block content %} 
    {% include 'components/message.html' %}
<form method="POST">

    {{ form.non_field_errors }}

    {% csrf_token %} <!--bir form gönderebilmek için bu eklenmeli validasyonla alakalı-->
    
    {{form | crispy }}   <!--oluşturduğumu iletişim formunu buraya direkt verince iletişim sayfasında yorumlanıyor html olarak navbar vs şeylere hala ihtiyaç var-->
    
    <input type="Submit" class="mt-3 mb-3" value= "Create">
</form>


{% endblock %}
    
    

SWE573_Project/templates/pages/details.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %} {{ article.title }} {% endblock %}

{% block content %}

    <head>
        <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.9.0/css/all.css">
        <link rel="stylesheet" href="../../static/css/details.css" type="text/css">
        <style>
            * {
            box-sizing: border-box;
            }

            .row {
            margin-left:-5px;
            margin-right:-5px;
            }

            .column {

            padding: 5px;
            }
            table {
            border-collapse: collapse;
            border-spacing: 0;
            width: 100%;
            border: 1px solid #ddd;
            }

            th, td {
            text-align: left;
           
            }

            tr:nth-child(even) {
            background-color: #f2f2f2;
            }
        </style>  
    </head>
    <style>#paragraph {
        text-align: justify;
    }</style>
    <body>
    <div class="card mb-3">
        <div class="row g-0">
            <div class="col-sm-12">
                <div id="full-text" class="card-body mb-3 selectable-text-area">
                    <h2 class="card-title">{{ article.title }}</h2>
                    <div id="slug" style="display: none;">{{ article.slug }}</div>
                    <div id="article_id" style="display: none;">{{ article.id }}</div>
                    <div id="csrf_token" style="display: none;">{% csrf_token %}</div>
                    <br>
                    <h6 class="card-text"><strong>Authors: </strong> {{ article.authors|safe }}</h6>
                    <h6 class="card-text"><strong>Publish Date:</strong> {{ article.publish_date }}</h6>
                    <h6 class="card-title"><strong>PMID:</strong> {{ article.pmid }}</h6>
                    <br>
                    <p id="headline" class="card-text"><strong>Abstract:</strong></p>
                    <p id="paragraph" class="card-text">{{ article.body }}
                        {% comment %}                            <!-- {% for text in article.body.split %}
                                <span class={{ text }}>{{ text }}</span>
                            {% endfor %} -->{% endcomment %}
                        {#                    <span class="highlight" {{ articleannotation.target }}></span>#}
                    </p>
                    <p class="card-text"><strong>Keywords:</strong> {{ article.keywords|safe }}</p>

                    <p class="card-text"><strong>Tags:</strong> {% for x in tags %}
                        <a target="_blank" href="{{ x.url }}">
                            <button>{{ x.name }}</button>
                        </a> {% endfor %}</p>
                    <p class="card-text"><strong>Annotations:</strong> {% for x in annotation_tags %}
                        <a target="_blank" href="{{ x.url }}">
                            <button>{{ x.name }}</button>
                        </a> {% endfor %}</p>
                        <p class="card-text"><strong>Annotated Text:</strong> {% for y in values %}
                            <p class="highlight" style="color:black">{{ y }}</p>
                        {% endfor %}
                        </p>
                    {#<p class="card-text"><small class="text-muted">Publish Date {{ article.publish_date }}</small></p>#}
                    <p class="card-text"><small class="text-muted">Last
                        Update {{ article.update_date|timesince }}</small></p>
                </div>
            </div>
        </div>
    </div>
    <input id="tag_ann"></input>
    <button id="plus-btn"><i class="fas fa-quote-right"></i>
        <p class="annotatetext">Annotate</p></button>
    <button onclick="window.open('{% url 'tag' article.id %}')" id="tag-btn"><i class="fas fa-tags"></i>
        <p class="tagtext">Tag</p></button>
    {#<button id="plus-btn"><a href="{% url 'tag' article.id %}"><i class="success">Annotate</i></a></button>#}

    <h6>
        <li class="list-group-item mb-3">
            <a href="{% url 'tag' article.id %}">Tag</a> <!--bir card başlığını linklemek için kullanılan yapı-->
        </li>
    </h6>
    <h6>
        {#        <li class="list-group-item mb-3">#}
        {#            <a href="{% url 'add_comment' article.id %}">Comment</a>#}
        {#            <!--bir card başlığını linklemek için kullanılan yapı-->#}
        {#        </li>#}
    </h6>
    <h6>
        <li class="list-group-item mb-3">
            <a href="{% url 'report' article.id %}">Report</a> <!--bir card başlığını linklemek için kullanılan yapı-->
        </li>
    </h6>
 
<div class="row">
    <div class="column"> 
        <table>
            <tr>
                <th>Annotation</th>
                <th>Link</th>
                <th>Creator</th>

            </tr>
            {% for x in annotation_tags %}
            <tr>
                <td><a target="_blank" href="{{ x.url }}">
                    <button>{{ x.name }}</button>
                </a></td>
                <td><a target="_blank" href="{{ x.url }}"><p>{{ x.url }}</p></a></td>
                <td><a href="{% url 'profile-detail' x.user.profile.id %}">{{ x.user }}</a></td>
            </tr>
            {% endfor %}
            
        </table>
    </div>

</div>

    <form method="post">
        {% csrf_token %}
        <div id="user-selection" class="form-group">
            <label for="user-selection"></label>
            <input id="text-selection" class="form-control" type="hidden" value="" name="text-selection" readonly>
            <input id="start-index" class="form-control" type="hidden" name="start-index" value="0">
            <input id="end-index" class="form-control" type="hidden" name="end-index" value="-1">
        </div>
    </form>

    </body>


{% endblock %}

{% block extra_script %}
    <script src="../../static/js/details.js"></script>
{% endblock %}

SWE573_Project/templates/pages/homepage.html
{% extends 'base.html' %}

{% block title %} Homepage {% endblock %}

{% block content %}

    <h4> 
      <br>
      Top recommendations for you:
      <br>
      <br>
    </h4>
{% for article in articles %}

<div class="card mb-3">
    <div class="row g-0">
      <div class="col-sm-12">
        <div class="card-body mb-3">
          <h5 class="card-title">
            <a href = "{% url 'details' slug=article.slug %}">
              {{ article.title }}
            </a>
          </h5>
          <h6 class="card-text">Author(s): {{ article.authors|safe }}</h6>
          <p class="card-text">{{ article.body|safe|truncatechars_html:300 }}</p>
          <p class="card-text">Keyword(s): {{ article.keywords|safe }}</p> 
          <p class="card-text"><small class="text-muted">Publish Date {{ article.publish_date }}</small></p>
          <p class="card-text"><small class="text-muted">MediSearch Publish Date {{ article.update_date }}</small></p>

        </div>
      </div>
    </div>
  </div>
{% empty %}

<p>We couldn't find any article related to your search.</p>

{% endfor %}

<div class="container p-4">
  <div class="pagination justify-content-center">
      <span class="step-links">
        {% if articles.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ articles.previous_page_number }}">previous</a>
        {% endif %}

          <span class="current">
              Page {{ articles.number }} of {{ articles.paginator.num_pages }}
          </span>

        {% if articles.has_next %}
            <a href="?page={{ articles.next_page_number }}">next</a>
            <a href="?page={{ articles.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
      </div>
  </div>

{% endblock %}

SWE573_Project/templates/pages/tag.html
{% extends 'base.html' %} <!--bir bas html dosyası oluşturduk çünkü hepsini üstüne kullanıcaz config seetings dir üstünde güncellemesi var-->
{% load crispy_forms_tags %} <!--crispy formları kullanabilmek için önce indirdik pipenv install diyip ardından html dosyalarına da koyuyoruz-->


{% block title %} Tag {% endblock %} <!--sayfanın başlığı-->

{% block content %} 
   
<form method="POST">
    {{ form.errors }}
    {% csrf_token %} <!--bir form gönderebilmek için bu eklenmeli validasyonla alakalı-->
    {{form | crispy }}   <!--oluşturduğumu iletişim formunu buraya direkt verince iletişim sayfasında yorumlanıyor html olarak navbar vs şeylere hala ihtiyaç var-->
    <p id="sonuc"></p>
    <button type="Submit" class="mt-3 mb-3">Send</button>
    <a href="javascript:history.back()"><button type="button" class="mt-3 mb-3">Back</button></a>

</form>


{% endblock %}

{% block extra_script %}
<script>

$( function() {
    var availableTags = [
    ];

    var link = "https://www.wikidata.org/w/api.php?action=wbsearchentities&format=json&errorformat=plaintext&language=en&uselang=en&type=item"


    $( "#id_name" ).autocomplete({
      source: function( request, response ) {
        $.ajax( {
          url: link,
          dataType: "jsonp",
          data: {
            search: request.term
          },
          success: function( data ) {
            var searchTerms = [];
            data.search.forEach(element => {
                searchTerms.push({
                    id: element.id,
                    label: element.label + " | " + element.description,
                    value: element.label,
                    desc: element.description,
                    url: element.url
                })
            });
            response(searchTerms);
          }
        } );
      },
      minLength: 2,
      select: function( event, ui ) {
        $('#sonuc').html(ui.item.desc);
        $('#id_url').val("https://"+ui.item.url.replace('//', ''));
      }
    } );



  } );
</script>
{% endblock %}